name: Run e2e tests
on:
  workflow_call:
    inputs:
      environment:
        description: "E2E Env Selector"
        type: string
        default: dev
  workflow_dispatch:
    inputs:
      environment:
        description: "E2E Env Selector"
        type: choice
        options:
          - dev
          - test
        default: dev

jobs:
  run_tests:
    name: Run E2E tests
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.51.1-noble@sha256:146d046a8d79a1b3a87596c4457b0b1c47f811bf4fc2cc1b99e873ae7f1cbbbd
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout e2e tests
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: true
      - name: Get current date
        shell: bash
        id: currentdatetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GithubCopilotDeploy
          role-session-name: COPILOT_${{ inputs.environment }}_FAB_${{ steps.currentdatetime.outputs.datetime }}
          aws-region: eu-west-2
      - name: Run tests
        run: uv run --frozen pytest --e2e --e2e-env ${{ inputs.environment }}
        env:
          E2E_DEVTEST_BASIC_AUTH_USERNAME: ${{ secrets.E2E_DEVTEST_BASIC_AUTH_USERNAME }}
          E2E_DEVTEST_BASIC_AUTH_PASSWORD: ${{ secrets.E2E_DEVTEST_BASIC_AUTH_PASSWORD }}
