name: Validate PR
on:
  push:
    branches-ignore: [ main ]

jobs:
  unit_tests:
    name: Run unit tests
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/pre-deploy.yml@main
    with:
      postgres_unit_testing: true
      db_name: fab_store_test

  paketo_build:
    name: Package and build application
    needs: [ unit_tests ]
    permissions:
      packages: write
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/package.yml@main
    with:
      version_to_build: sha-${{ github.sha }}
      owner: ${{ github.repository_owner }}
      application: funding-service-design-fund-application-builder
      assets_required: true

  e2e_tests:
    name: Run E2E tests
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.51.1-noble@sha256:146d046a8d79a1b3a87596c4457b0b1c47f811bf4fc2cc1b99e873ae7f1cbbbd
    services:
      postgres:
        image: postgres@sha256:3962158596daaef3682838cc8eb0e719ad1ce520f88e34596ce8d5de1b6330a1
        env:
          POSTGRES_PASSWORD: password # pragma: allowlist secret
          POSTGRES_USER: postgres # pragma: allowlist secret
          POSTGRES_DB: fab_store # pragma: allowlist secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Install uv with Caching
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: true
      - name: Apply Database Migrations
        run: uv run --frozen flask db upgrade
        env:
          DATABASE_URL: postgresql://postgres:password@postgres:5432/fab_store # pragma: allowlist secret
      - name: Start Mock Pre-Award API
        run: uv run --frozen python tests/e2e/mock_pre_award.py &
      - name: Start Flask Application
        run: uv run --frozen flask run --no-debugger --host 0.0.0.0 --port 8080 &
        env:
          DATABASE_URL: postgresql://postgres:password@postgres:5432/fab_store # pragma: allowlist secret
          RSA256_PUBLIC_KEY_BASE64: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZU1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTUFEQ0JpQUtCZ0hHYnRGMXlWR1crckNBRk9JZGFrVVZ3Q2Z1dgp4SEUzOGxFL2kwS1dwTXdkU0haRkZMWW5IakJWT09oMTVFaWl6WXphNEZUSlRNdkwyRTRRckxwcVlqNktFNnR2CkhyaHlQL041ZnlwU3p0OHZDajlzcFo4KzBrRnVjVzl6eU1rUHVEaXNZdG1rV0dkeEJta2QzZ3RZcDNtT0k1M1YKVkRnS2J0b0lGVTNzSWs1TkFnTUJBQUU9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==" # pragma: allowlist secret
          FORM_STORE_API_HOST: http://localhost:8081
      - name: Execute End-to-End Tests
        run: uv run --frozen pytest --e2e --e2e-env e2e
